"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase/client";

export function AcessoCliente() {
  const router = useRouter(); const [novo, setNovo] = useState(false); const [nome, setNome] = useState(""); const [telefone, setTelefone] = useState(""); const [email, setEmail] = useState(""); const [senha, setSenha] = useState(""); const [mensagem, setMensagem] = useState("");
  async function enviar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setMensagem(""); if (novo) { const { data, error } = await supabase.auth.signUp({ email, password: senha }); if (error || !data.user) return setMensagem(error?.message ?? "Não foi possível criar a conta."); const { error: cadastroError } = await supabase.from("clientes").insert({ id: data.user.id, nome, telefone: telefone || null }); if (cadastroError) return setMensagem("Conta criada, mas não foi possível salvar seus dados."); setMensagem("Conta criada. Você já pode entrar."); setNovo(false); return; } const { error } = await supabase.auth.signInWithPassword({ email, password: senha }); if (error) return setMensagem("E-mail ou senha inválidos."); router.push("/conta"); }
  return <main className="grid min-h-screen place-items-center bg-stone-950 p-4"><form onSubmit={enviar} className="w-full max-w-sm rounded-3xl bg-white p-6"><p className="text-sm font-bold uppercase tracking-widest text-orange-500">PedeAI</p><h1 className="mt-2 text-2xl font-bold text-stone-900">{novo ? "Criar conta" : "Minha conta"}</h1><div className="mt-5 space-y-3">{novo && <><input required value={nome} onChange={(e)=>setNome(e.target.value)} placeholder="Seu nome" className="campo"/><input value={telefone} onChange={(e)=>setTelefone(e.target.value)} placeholder="WhatsApp" className="campo"/></>}<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="E-mail" className="campo"/><input required type="password" minLength={6} value={senha} onChange={(e)=>setSenha(e.target.value)} placeholder="Senha (mínimo 6 caracteres)" className="campo"/>{mensagem && <p className="text-sm text-orange-700">{mensagem}</p>}<button className="w-full rounded-xl bg-orange-500 py-3 font-bold text-white">{novo ? "Criar conta" : "Entrar"}</button><button type="button" onClick={()=>setNovo(!novo)} className="w-full py-2 text-sm font-semibold text-stone-600">{novo ? "Já tenho uma conta" : "Ainda não tenho conta"}</button></div></form></main>;
}
